### PR TITLE
Add support for tvOS in Podspec

### PR DESCRIPTION
**Pull request by lrossi**

### CODE REVIEW

**Comment by ldiqual** [comment]
Thanks @lrossi for your contribution! I'll look into this a bit more since we need to make sure that it passes the `pod spec lint` validation + unit tests on the tvOS platform. I'll get back to you soon on this.

**Comment by lrossi** [comment]
Sure, thanks! FYI, I'm using Kugel in a tvOS project and it compiles and works just fine as it is so far.

**Comment by lrossi** [comment]
Also, I created a tvOS framework target in the main Kugel project with the same tests as the iOS one:

https://github.com/lrossi/Kugel/tree/tvOS-tests

The tests are passing just fine on tvOS as well.

(I can merge the branch into my PR, but of course only if this is the way you want to go.)

**Comment by ldiqual** [comment]
@lrossi That's awesome, glad to hear it works there. Why do you need a separate target? Can't cocoapods just generate the appropriate framework according to your platform? Or is it just for test purposes?
Looking at your branch, I don't see tvOS-specific tests (and that's probably fine since it's covered in KugelTests), am I missing something?

**Comment by lrossi** [comment]
> Can't cocoapods just generate the appropriate framework according to your platform?

Yes, the additional line in the Podspec is all I needed to properly import the pod into my tvOS project.

> Or is it just for test purposes?

Yes, in the `tvOS-tests` branch I added a new `Kugel_tvOS` framework target (together with the corresponding `Kugel_tvOSTests` target) to the `Kugel.xcodeproj` project file to be able to execute the tests on the tvOS platform.

> Looking at your branch, I don't see tvOS-specific tests (and that's probably fine since it's covered in KugelTests), am I missing something?

No you're right, I simply re-added the same `KugelTests.swift` file you wrote to the new tvOS test target.

**Comment by ldiqual** [comment]
Alright, seems all good! Let me know if you want a new version on cocoapods to integrate with your project ;) Thanks a lot for your contribution.

**Pull request merged**
